/**
 * Shared mutable application state (former top-level let/const collections).
 * Import as: import { state } from './state.js';
 */
export const state = {
  currentTitleText: 'Ready',
  activeBgLayer: 'a',
  queuePlaylistSaved: false,
  queueSavePlaylistMode: false,
  uiTimeout: undefined,
  isPlaying: false,
  duration: 0,
  currentPos: 0,
  progressRaf: null,
  progressAnchorMs: 0,
  progressAnchorAt: 0,
  progressAnchorSpeed: 1,
  artUrlCache: new Map(),
  artUrlsNoCors: new Set(),
  themePrefetchCache: new Map(),
  _prefetchQueueKey: '',
  _prefetchInFlight: false,
  _prefetchGen: 0,
  sendspinAuthorityKey: '',
  lastPlaybackMediaKind: '',
  trackExtrasCache: new Map(),
  trackExtrasProbeGen: 0,
  nowPlayingTrackExtras: {
    trackKey: '',
    hasOtherVersions: false,
    hasSimilarTracks: false,
  },
  _lastVizPaletteKey: '',
  npTextTrackKey: '',
  _bgCrossfadeTimer: null,
  _bgOutgoingLayer: null,
  _bgLastCrossfadeImage: '',
  _npEffectsTimer: null,
  albumArtistCache: new Map(),
  npVisuals: {
    generation: 0,
    trackKey: '',
    artUrl: '',
    accentReady: false,
    status: 'idle',
    debounceTimer: null,
    inFlight: null,
    pendingApply: null,
    appliedAccentKey: '',
    stableArtUrl: '',
    lastAppliedAccentColor: '',
    pendingAccent: null,
  },
  navGenresMenuOpen: false,
  navGenresCache: [],
  navGenreFocusIndex: 0,
  navGenreMenuEls: [],
  navArtistsMenuOpen: false,
  navArtistsCache: [],
  navArtistFocusIndex: 0,
  navArtistMenuEls: [],
  navArtistsSourceMedia: null,
  maCatchupTimer: null,
  lastProgressTrackId: '',
  progressResyncAt: 0,
  progressSpinGuardUntil: 0,
  maQueueAuthorityUntil: 0,
  progressAuthorityMode: 'ma',
  seekAuthorityMs: 0,
  seekAuthorityUntil: 0,
  lastSendspinStreamGen: 0,
  lastSendspinTrackKey: '',
  remoteSeekHoldDelay: null,
  remoteSeekHoldIv: null,
  remoteSeekActive: false,
  cursorIdleTimer: null,
  focusIndex: 2,
  uiFocusZone: 'controls',
  playbackFocusIndex: 2,
  topBarFocusIndex: 0,
  menuFocusIndex: 0,
  settingsMenuOpen: false,
  navMenuOpen: false,
  volumeMenuOpen: false,
  eqPresetsMenuOpen: false,
  vizModesMenuOpen: false,
  artDisplayMenuOpen: false,
  artDisplayFocusIndex: 0,
  artDisplayMenuEls: [],
  lyrics: {
    trackKey: '',
    loading: false,
    hasLines: false,
    lrcLines: null,
    plainLines: null,
    activeIndex: -1,
    synced: false,
    fetchGen: 0,
    retryTimer: null,
    lastLayoutOpts: {},
    idleFocused: false,
    manualScrollUntil: 0,
    plainScrollAutoTop: 0,
    plainScrollUserOffset: 0,
    plainScrollHover: false,
    plainScrollUserHold: false,
    plainScrollResumeTimer: null,
    plainScrollLastTs: 0,
  },
  eqPresetFocusIndex: 0,
  eqPresetMenuEls: [],
  eqPresetsCache: [],
  vizModeFocusIndex: 0,
  vizSelectorIconFocus: 0,
  vizModeMenuEls: [],
  volumeFocusIndex: 0,
  volumeFocusOrder: ['local', 'close'],
  playerVolumeLevel: null,
  playerVolumeMuted: false,
  playerVolumeControl: 'native',
  volumeGroupLevel: null,
  volumeGroupMuted: false,
  volumeGroupLeaderId: null,
  volumeGroupSnapshot: null,
  volumeMemberStates: new Map(),
  volumeMemberTimers: new Map(),
  volumeSetTimer: null,
  volumeGroupSetTimer: null,
  navMenuFocusIndex: 0,
  browsePanelOpen: false,
  detailsPanelOpen: false,
  detailsPanelRows: [],
  detailsPanelMedia: null,
  detailsPanelQueueItem: null,
  queuePanelOpen: false,
  playersPanelOpen: false,
  playersFocusZone: 'list',
  queueFocusZone: 'list',
  queueActionFocusIndex: 0,
  playersRowSubFocus: 0,
  playersStereoPairExpanded: false,
  _deferredOffsetApplyTimer: null,
  _pendingPlaybackOffsets: null,
  playersLoading: false,
  playersListCache: [],
  playersSyncSelected: new Set(),
  playersSyncSelectedOrder: [],
  playersActiveGroup: null,
  playersRemoteGroup: null,
  playersActionFocusIndex: 0,
  playersRefreshTimer: null,
  playersPanelRenderKey: '',
  playerSyncDelayCache: new Map(),
  playerGroupTrimCache: new Map(),
  playerSyncDelayConfigKeyCache: new Map(),
  syncGroupCorrectionMode: '',
  syncDelayResyncTimer: null,
  syncDelayResyncLastAt: 0,
  syncDelayResyncPending: false,
  syncDelayResyncAdjustedPlayerId: null,
  audioHealthEmptyStreak: 0,
  /** Android search: chips collapsed this session only (default expanded). */
  androidChipSectionsCollapsed: {},
  androidSearchChipsCollapsed: false,
  containerActionQueuedState: new Map(),
  localSyncLeaderId: '',
  lastLocalSyncStateKey: '',
  tvLibraryBootstrapped: false,
  lastLocalPlayerMediaKey: '',
  localVisualCatchupTimer: null,
  browseStack: [{ key: 'root', title: 'Browse', type: 'root' }],
  /** 'manual' = opened via Browse and drilled down; 'shortcut' = Go-to / jump stack. */
  browseEntryMode: 'manual',
  browseViews: {},
  _browseViewOrder: [],
  _defaultVolumeApplied: false,
  _browseSearchGeneration: 0,
  artistProvidersCache: new Map(),
  _lastBrowseRenderKey: '',
  _lastBrowseLayout: '',
  _browseRenderRaf: 0,
  panelFocusIndex: 0,
  panelInputMode: 'keyboard',
  lastFocusInput: 'keyboard',
  queueRowMenuOpen: false,
  queueRowMenuIndex: -1,
  queueMenuFocusIndex: 0,
  queueMenuActionEls: [],
  queueMenuActions: [],
  queueRowSubFocus: 0,
  queueReorderMode: false,
  queueReorderIndex: -1,
  queueReorderItemId: '',
  queueReorderDragging: false,
  queueReorderMoveInFlight: false,
  queueReorderDragTarget: -1,
  queueReorderDragStartIndex: -1,
  queueReorderDragStepY: null,
  queueReorderDragRowHeight: 48,
  queueReloadTimer: null,
  queueReloadPending: false,
  queueReloadForce: false,
  queueItems: [],
  browseRowSubFocus: 0,
  browseRowMenuOpen: false,
  browseRowMenuIndex: -1,
  browseRowMenuItem: null,
  browseMenuFocusIndex: 0,
  browseMenuActionEls: [],
  browseMenuActions: [],
  playersRowMenuOpen: false,
  playersRowMenuIndex: -1,
  playersRowMenuTarget: null,
  playersMenuFocusIndex: 0,
  playersMenuActionEls: [],
  playersRowMenuActions: [],
  browseFocusZone: 'list',
  detailsFocusZone: 'list',
  searchFilterFocusIndex: 0,
  searchMediaFilter: (() => {
    try {
      const raw = localStorage.getItem('spinstage_search_ui_prefs');
      if (!raw) return 'all';
      const saved = JSON.parse(raw);
      const ids = ['all', 'artist', 'album', 'track', 'playlist', 'audiobook', 'radio', 'podcast'];
      return ids.includes(saved.mediaFilter) ? saved.mediaFilter : 'all';
    } catch {
      return 'all';
    }
  })(),
  lastSearchQuery: '',
  searchProviderOptions: [{ id: 'library', name: 'Library', enabled: true }],
  searchProvidersReady: false,
  providerMenuOpen: false,
  providerMenuFocusIndex: 0,
  artistProviderFocusIndex: 0,
  alphaViewFocusIndex: 0,
  containerActionFocusIndex: 0,
  containerMenuActions: [],
  queueTotalCount: 0,
  queueListOffset: 0,
  lastQueueContext: '',
  queueLoading: false,
  lastNowPlayingKey: '',
  _nowPlayingGeneration: 0,
  _bgBakeItemKey: '',
  _lastArtUpdateKey: '',
  _lastArtAppliedUrl: '',
  audiobookAuthorCache: new Map(),
  podcastNameCache: new Map(),
  radioSubtitleCache: new Map(),
  lastPodcastShowSubtitle: '',
  lastRadioStationFallback: '',
  lastRadioStationFallbackUri: '',
  lastRadioStreamMetaKey: '',
  lastSendspinMetadata: null,
  browseListLoading: false,
  browsePagePending: false,
  browsePagePendingReset: false,
  shuffleEnabled: false,
  repeatMode: 'off',
  lastLocalModeChange: 0,
  musicProvidersCache: { ready: false, list: [], loadedAt: 0 },
  browseProviderContentCache: new Map(),
  radioCatalogCache: new Map(),
  radioMergedCatalogCache: new Map(),
  favoritesListCache: null,
  _navPlaylistContext: null,
};
